CREATE DATABASE IF NOT EXISTS nesta CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE nesta;
CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,role ENUM('user','admin') NOT NULL DEFAULT 'user',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE properties (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(180) NOT NULL,description TEXT NOT NULL,city VARCHAR(100) NOT NULL,address VARCHAR(190) NOT NULL,price DECIMAL(14,2) NOT NULL,area DECIMAL(8,2) NOT NULL,rooms TINYINT UNSIGNED NOT NULL,type VARCHAR(50) NOT NULL,image VARCHAR(500) NOT NULL,status ENUM('active','draft') NOT NULL DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(city),INDEX(price));
CREATE TABLE favorites (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,property_id INT UNSIGNED NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY user_property(user_id,property_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE CASCADE);
INSERT INTO users(name,email,password,role) VALUES ('NESTA Admin','admin@nesta.local','$2y$10$3QMiRoVsBu3MahhqIXtl/O1ysxb8VZJYngcigjgV/IMXkRhzZac06','admin');
INSERT INTO properties(title,description,city,address,price,area,rooms,type,image,status) VALUES
('Modern Apartment','A quiet, beautifully proportioned apartment with natural light, refined finishes and a walkable city setting.','Vladivostok','Center, Svetlanskaya 45',8500000,72,2,'Apartment','https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80','active'),
('Ocean View Residence','An elevated waterfront residence with expansive glazing and a peaceful view of the bay.','Vladivostok','Egersheld, Leitenanta Shmidta 11',18900000,118,3,'Apartment','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80','active'),
('Minimal House','A warm, minimal home designed for a slower family rhythm, with a private garden.','Artem','Zolotaya Dolina 8',14200000,156,4,'House','https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80','active'),
('Downtown Loft','A characterful loft in the heart of the city with high ceilings and thoughtful details.','Vladivostok','Center, Aleutskaya 17',11200000,86,2,'Loft','https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80','active'),
('Family Residence','A spacious residence near green spaces, designed for everyday comfort.','Ussuriysk','Parkovaya 23',9700000,132,4,'House','https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80','active'),
('Luxury Villa','A secluded villa with generous living spaces, terraces and exceptional privacy.','Vladivostok','Sadgorod, Morskaya 6',38500000,310,5,'Villa','https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80','active');
